# Generated by Django 4.2.9 on 2024-01-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='Name of category')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('activate', models.BooleanField(default=False, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'categories',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
    ]
