# Generated by Django 4.2.9 on 2024-01-05 16:55

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=djrichtextfield.models.RichTextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=25, unique=True, verbose_name='Имя категории'),
        ),
    ]
