# Generated by Django 4.2.9 on 2024-01-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_category_email_category_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Updated')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='Goods name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('activate', models.BooleanField(default=False, verbose_name='Active')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=25, unique=True, verbose_name='Category name'),
        ),
    ]
