# Generated by Django 4.2.9 on 2024-01-05 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_goods_delete_post_alter_category_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ['name'], 'verbose_name': 'product', 'verbose_name_plural': 'goods'},
        ),
    ]
