# Generated by Django 4.2.9 on 2024-01-08 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_goods_email_goods_url_alter_goods_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='catalog.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goods',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Updated'),
        ),
    ]
