# Generated by Django 4.2.9 on 2024-01-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_tag_goods_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='image',
            field=models.ImageField(blank=True, upload_to='image', verbose_name='Image'),
        ),
    ]
